language: erlang
branches:
        only:
                - master
notifications:
        email: michal@ptaszek.net
otp_release:
        - 17.0-rc1
        - R16B03-1
        - R16B03
        - R16B02
        - R16B01
